# Generated by Django 4.1.7 on 2023-08-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendancemodel',
            new_name='Attendance',
        ),
    ]
