# Generated by Django 4.1.7 on 2023-09-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_bill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalDoubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('reply', models.TextField(max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
