# Generated by Django 4.1.7 on 2023-09-11 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_medicaldoubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldoubt',
            name='Cuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
