# Generated by Django 4.1.7 on 2023-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_creditcard_bill_alter_bill_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
