# Generated by Django 4.1.7 on 2023-06-06 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_appointment_end_time_appointment_physician_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='physician_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
